### ISSUE TITLE
Scaling too quickly triggers a crash

### ISSUE THREAD

**Issue by colinmford** [ohnotypeco/Transmutor-Ext#18]
Might just be my system, but scaling a glyph too quickly causes a crash, perhaps because too many calls for interpolation in rapid succession.

Potential solution is to clean up the script so there are not as many method calls, and/or put a limit so that if too much is happening quickly there is some sort of pause before resuming.

**Comment by connordavenport** [comment]
ahhhh I was running into this the other day but I thought it was my tool conflicting with the extension! https://discord.com/channels/1052516637489766411/1055056244529958982/1161697857712177152

**Comment by colinmford** [comment]
@connordavenport try the new version, I haven't had issues after making an adjustment

**Comment by colinmford** [comment]
I haven't had an issue since making the updates to 2.0.3 so I'm calling this fixed.

**Comment by colinmford** [comment]
Anecdotally, this seems to happen most often when scaling a glyph with 0 width, like a combining accent

**Comment by colinmford** [comment]
This also happens most often when using the "one dimension" handles (i.e. not the corner handles)
