### ISSUE TITLE
Tool should be just a window instead of an edit tool?

### ISSUE THREAD

**Issue by colinmford** [ohnotypeco/Transmutor-Ext#3]
There are benefits to both approaches.

If Transmutor was a window, you could use other tools with it (like the measurement tool @connordavenport just added. Or edit an outline. A drawback would be managing all of the edge cases that might occur when the user isn't _just_ using the tool.

Keeping it as a tool simplifies the situation because you know the tool has the user's attention.

Inspiration for the window method include Outliner and Rotator.

An open debate.

**Comment by ryanbugden** [comment]
One benefit to this would be to adjust existing contours while Transmuting prospective ones (e.g. the ring around a `registered` while Transmuting an `R`)

One issue you might run into is how well you'll be able to control other interactions (e.g. https://github.com/frankrolf/Rotator/issues/4), but honestly, I can't think of too many things you'd want to stop from happening. Maybe only disable marquee if scaling in glyph editor with your mouse.

See commented out lines here, for what I couldn't get to work: https://github.com/frankrolf/Rotator/blob/8af6fbe9ee2d5736a4ce894a414e28e76a4b9ead/Rotator.roboFontExt/lib/rotator.py#L399

**Comment by colinmford** [comment]
Made it a window instead of a tool for v2.0
